name: CI

on: [push, pull_request]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test
